### ISSUE TITLE
latest update killed it

### ISSUE THREAD

**Issue by 0fxyzSa0vj** [yourdawi/MMM-HomeAssistant#2]
Is there a way to add a label to the entity value? I have my fridge temperature displaying but there is not label or title, just the temperature displayed.  

Thank you

**Comment by yourdawi** [comment]
I will rewrite some code and extend the features soon.
I will add a config option to use the friendly name out of home assistant, set a custom name only for MagicMirror or disable the name, just showing the value.
Maybe i can push this tomorrow.

**Comment by yourdawi** [comment]
@0fxyzSa0vj  
Please update and add "useFriendlyName: true/false" in your config (default is true, so if you want to use the friendlyname, you can skip this and just update.
If you use "useFriendlyName: false" you can also add displayName: "custom name" to display a custom name.

I wrote it from my phone, but it should work

**Comment by 0fxyzSa0vj** [comment]
Thank you for the quick response, I edited my config to add useFriendlyName: false and added a displayName, still just showing the entity value.  I also tried use FriendlyName: true, still just the entity value.

{ entity_id: "sensor.fridge_temperature_temperature", useFriendlyName: false, displayName: "Fridge" },

**Comment by yourdawi** [comment]
@0fxyzSa0vj  

Did you redownload the Plugin?
I changed the code for this.

**Comment by 0fxyzSa0vj** [comment]
I didn't. 

I just did redownload the plugin and now I get undefined for the entity value. Access token is valid.

**Comment by yourdawi** [comment]
@0fxyzSa0vj  

Thanks for the reply, i will check this and mention you when i fixed it, i will test it on my mirror.
Any features whishes i can implement while i am doing this?

**Comment by 0fxyzSa0vj** [comment]
Thanks. I can't think of any additional features right now.

**Comment by yourdawi** [comment]
@0fxyzSa0vj 

I fixed it. Please redownload and take a look in the readme, i changed the config layout.

**Comment by 0fxyzSa0vj** [comment]
works great, thanks!
